http:
  routers:
    jellyfin:
      rule: "Host(`jellyfin.home.kurup.net`)"
      entryPoints: [websecure]
      service: jellyfin
      tls:
        certResolver: cloudflare
        domains:
          - main: "home.kurup.net"
            sans:
              - "*.home.kurup.net"

    sonarr:
      rule: "Host(`sonarr.home.kurup.net`)"
      entryPoints: [websecure]
      service: sonarr
      tls:
        certResolver: cloudflare

    radarr:
      rule: "Host(`radarr.home.kurup.net`)"
      entryPoints: [websecure]
      service: radarr
      tls:
        certResolver: cloudflare

    prowlarr:
      rule: "Host(`prowlarr.home.kurup.net`)"
      entryPoints: [websecure]
      service: prowlarr
      tls:
        certResolver: cloudflare

    bazarr:
      rule: "Host(`bazarr.home.kurup.net`)"
      entryPoints: [websecure]
      service: bazarr
      tls:
        certResolver: cloudflare

    deluge:
      rule: "Host(`deluge.home.kurup.net`)"
      entryPoints: [websecure]
      service: deluge
      tls:
        certResolver: cloudflare

    sabnzbd:
      rule: "Host(`sabnzbd.home.kurup.net`)"
      entryPoints: [websecure]
      service: sabnzbd
      tls:
        certResolver: cloudflare

    calibre-web:
      rule: "Host(`books.home.kurup.net`)"
      entryPoints: [websecure]
      service: calibre-web
      tls:
        certResolver: cloudflare

    homepage:
      rule: "Host(`home.kurup.net`)"
      entryPoints: [websecure]
      service: homepage
      tls:
        certResolver: cloudflare

    traefik:
      rule: "Host(`traefik.home.kurup.net`)"
      entryPoints: [websecure]
      service: api@internal
      tls:
        certResolver: cloudflare

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8096"

    sonarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8989"

    radarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:7878"

    prowlarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:9696"

    bazarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:6767"

    deluge:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8112"

    sabnzbd:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8080"

    calibre-web:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8083"

    homepage:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:3000"
